### ISSUE TITLE
List hub.docker.com container in README

### ISSUE THREAD

**Issue by jeremydouglass** [inklewriter/freeinklewriter#12]
* **I'm submitting a ...**
  - [x] feature request

Would it make sense to list the official build docker container in the README? I believe (?) that it is:

https://hub.docker.com/r/albancrommer/inklewriter

**Comment by albancrommer** [comment]
The README file mentions the docker-compose file which uses the said docker image.

For the app to work, you need a postgresql database backend, hence the use of docker-compose which connects the db to the ruby app.

So I'm not sure it would be wise to just mention the raw docker image.

Although, it might we a good idea to make the README be more explicit? What do you think?

**Comment by jeremydouglass** [comment]
Got it.

I'm using docker swarm with docker-compose.yml, thinking about deployment testing -- so I'll check out the -system repo.

As I mentioned in a comment on

1c4bc83994d55d3cb5cbfe62f335ba78e0f24490

...I was considering opening an issue and submitting a PR for something no-build -- so it would use env variables and/or docker secrets rather than downloading the repo and editing an .env file. 

I'll look at it and consider opening something there.

This issue closed by cf3a831a185b9bad56871d8c7a384f70c2af6e00
