### ISSUE TITLE
Add option for users to reset their own password

### ISSUE THREAD

**Issue by dreese** [inklewriter/freeinklewriter#13]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
There doesn't appear to be a way to reset my own password. Once lost or forgotten, I can no longer sign in.

* **What is the expected behavior?**
It would be great if the Sign In page had a link called something like "Forgot your password?" If clicked, the link would prompt the user to reset their password by entering in their email address. Then they would receive a link that would allow them to enter a new password (probably twice for safety).
* **What is the motivation / use case for changing the behavior?**
Contacting the developer is possible, but takes time for both people. Automating the process could be very helpful in removing the need to spend time manually resetting passwords for other people.

* **Please tell us about your environment:**
I'm using macOS 10.15.4 but I suspect the feature would work the same on all platforms.

**Comment by albancrommer** [comment]
This feature is being implemented. More on that soon.

**Comment by albancrommer** [comment]
The feature is now merged and available in production after 4b98208

**Comment by dreese** [comment]
Thank you!
