### ISSUE TITLE
Welcome not centered on resize

### ISSUE THREAD

**Issue by jeremydouglass** [inklewriter/freeinklewriter#15]
* **I'm submitting a ...**
  - [x] feature request
 
* **What is the current behavior?**

1. Load inklewriter while signed out. A centered "welcome" appears.
2. Resize the window.

Expected: centered "welcome" is centered
Current: "welcome" does not move -- is covered by small screen or left-aligned on bigger screen.

* **What is the motivation / use case for changing the behavior?**
Minor issue that creates a better desktop experience.

* **Please tell us about your environment:**
  - Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by albancrommer** [comment]
Confirmed. That would be good to fix. 
The "Dialog" (i.e. modals) management system doesn't manage resizing the window/viewport.
To achieve that, a list of active modals needs to be added.

**Comment by albancrommer** [comment]
This has been fixed. Now live in production on https://www.inklewriter.com

**Comment by jeremydouglass** [comment]
@albancrommer -- strange. I tried force-reloading the site, and the dialog remains fixed in place while I resize the window in Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by albancrommer** [comment]
It seems your browser uses a cache version, one way or another. I am certain the production js file contains the (minified) lines 
```
$(window).on("resize", ()=>{
    $(".dialogue").each((t,e)=>{
        $(e).css("top", ($(window).innerHeight() - $(e).height()) / 2),
        $(e).css("left", ($(window).innerWidth() - $(e).width()) / 2)
    }
    )
}
)

**Comment by jeremydouglass** [comment]
Odd. Just tried in two different browsers, two different devices, and incognito modes. It failed to resize on all of them.

https://www.inklewriter.com/

<img width="542" alt="Screen Shot 2020-05-15 at 11 45 29 AM" src="https://user-images.githubusercontent.com/798570/82085402-d410e700-96a1-11ea-8f55-db1711e2dd75.png">

Here it is in Firefox after I load the page, then drag the lower right corner of the browser window around. As I resize the window, the dialog remains fixed in place rather than centering, and it is cut off.

**Comment by albancrommer** [comment]
Ah, sorry you were absolutely right. This UI box doesn't share the "dialogue" class, it has its own "splash" class. Fixing that right now!

**Comment by albancrommer** [comment]
This is now fixed and pushed to production, can you confirm it's OK, @jeremydouglass ?

**Comment by jeremydouglass** [comment]
Looks great, thanks so much!
