### ISSUE TITLE
Feature request: integrate inklewriter to ink converter

### ISSUE THREAD

**Issue by joethephish** [inklewriter/freeinklewriter#16]
Currently it's possible to convert inklewriter stories to ink using [our (inkle's) converter page](https://www.inklestudios.com/inklewriter/to-ink/).

However it can run on the client because it's written in JavaScript (actually, TypeScript), and is [open source and on github](https://github.com/inkle/inklewriter-to-ink), so it would be pretty easy to add an option to inklewriter to allow you to download an inklewriter story as ink, to import into ink-based workflows.

It could be helpful for writers who start by drafting a story in inklewriter, but then want to expand upon it and use the more powerful ink toolchain?

**Comment by albancrommer** [comment]
Great idea, not be too hard and very useful.

Interface wise, I think adding an "Export" button would work well.

It would provide JSON and INK as options for now, and more if ever needed.

**Comment by joethephish** [comment]
Sounds great!

For JSON you might want to have a little note to say that it’s not compatible with the JSON that can be imported into the ink runtime. If there’s space in the UI to say that succinctly...!

**Comment by jeremydouglass** [comment]
The "share" dialog is here:

https://github.com/inklewriter/freeinklewriter/blob/master/app/assets/javascripts/pages/index.js#L9277

Currently it is the semi-secret json export option -- open share, then add .json to what you get.

I could imagine it instead offering three links:

- A play link /stories/1234
- A json link  /stories/1234.json
- An ink link  /stories/1234.ink

**Comment by albancrommer** [comment]
It has been added to the source code since 35bec194863fb52afd8

It should be pushed to production tomorrow.

**Comment by joethephish** [comment]
Awesome, thanks!

**Comment by albancrommer** [comment]
For now, we don't render an ink file. We just integrated your web page as a view and push the JSON structure into it. 

From an architectural point of view, we felt it was unsafe to fork nodejs threads from the Ruby process.

Later on we might come with a "Convert to Ink" API which would work serverless or in a nodejs docker and use that.

**Comment by joethephish** [comment]
Oh, but you could just include the compiled JS file on the client and call the convert function. It's [right here](https://www.inklestudios.com/inklewriter/to-ink/dist/inklewriter-convert.js).

Feel free to hack it to remove the export/modules stuff and rename the function so you can call it directly?

You could also use this client-side file download code?

```
        // Make a filename based on the authored story name? And pass in the converted text of the story.
        download_file(convertedInkFilename, convertedInk);
        

        // Yay, stackoverflow coding!
        // https://stackoverflow.com/questions/8310657/how-to-create-a-dynamic-file-link-for-download-in-javascript
        function download_file(name, contents, mime_type) {
            mime_type = mime_type || "text/plain";

            var blob = new Blob([contents], {type: mime_type});

            var dlink = document.createElement('a');
            dlink.download = name;
            dlink.href = window.URL.createObjectURL(blob);
            dlink.onclick = function(e) {
                // revokeObjectURL needs a delay to work properly
                var that = this;
                setTimeout(function() {
                    window.URL.revokeObjectURL(that.href);
                }, 1500);
            };

            dlink.click();
            dlink.remove();
        }
```

**Comment by albancrommer** [comment]
Sorry, I misexplained. We did exactly what you're describing. 

When I said "your page" I meant "the code available in the HTML file of the inklewriter-to-ink repository".

**Comment by joethephish** [comment]
Oh great, ok! 👍

**Comment by albancrommer** [comment]
Now available in production, example : https://www.inklewriter.com/stories/5284.ink

**Comment by joethephish** [comment]
Awesome, nice one!
