### ISSUE TITLE
URL preview showing a different story teaser

### ISSUE THREAD

**Issue by cliftonb** [inklewriter/freeinklewriter#18]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Trying to report a bug, but I have no idea how this works.

* **What is the current behavior?**
When an inklewriter URL is shared via text, a short snippet from a presumably different story is shared in the preview window. This is using the stock Android Messages app, but I imagine any app that displays URL previews will have the same behavior.

Here's my tweet showing two different stories with the same preview text. None of those stories include that text.
https://twitter.com/CliftonB/status/1257393102794428417

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

This is all a lot of steps to report something that was pretty clear in that tweet, but:
1. Create an inklewriter story
2. Hit Share and copy then URL provided
3. Paste the URL in an SMS to someone

* **What is the expected behavior?**
If anything, I'd expect to thee the title of the story, followed by the author's name.

* **What is the motivation / use case for changing the behavior?**
It would be less confusing for end users who would expect the preview to be representative of the story

* **Please tell us about your environment:**
It happens in the Android Messages app and Android Messages for Web in Chrome.

  
  - Version: 1.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues

**Comment by albancrommer** [comment]
The reason is pretty simple and related to the way we recovered and rebuilt the app from HTML capture.

To fix the bug, these informations should be added to any "View Story" HTML page:

- Title of the page should be the title of the story + author
- Title, author and first stitch should be the preliminary HTML content

Such as:

```

<div class="chunk">

    
   <h1>The Adventure of the Musgrave Ritual</h1>
   <h2>Sir Arthur Conan Doyle</h2>
    
    
   <div class="stitch_block">
   <div class='stitch openingStitch'>
   &lt;i&gt;From the &lt;b&gt;Memoirs of Sherlock Holmes&lt;/b&gt;.&lt;/i&gt;
   </div>
   </div>
    
   <!-- Initial options -->
   <div class="stitchBlock">
   <div class='option_button'>Part One: A Cold Night in London</div>
   </div>
    
   </div>

```
Instead of this, which appears for every story:

```

<div class="chunk">
    
    
   <!-- Initial options -->
   <div class="stitchBlock">
   <div class='option_button'>&quot;Well, just one then.&quot;</div>
   <div class='option_button'>&quot;No, I really must go.&quot;</div>
   </div>
    
   </div>
    
   </div>

```

**Comment by jeremydouglass** [comment]
https://github.com/inklewriter/freeinklewriter/blob/131e38d717b8e5e750e3e42ebf43fccdd466434c/app/views/stories/show.html.erb#L74-L77

**Comment by albancrommer** [comment]
It is now fixed and live in production cf. https://www.inklewriter.com/stories/5284

**Comment by jeremydouglass** [comment]
Tested here:

https://twitter.com/jeremydouglass/status/1258442516329684992
