### ISSUE TITLE
.ink export pane is partially hidden and not selectable

### ISSUE THREAD

**Issue by jeremydouglass** [inklewriter/freeinklewriter#19]
- [x] bug report

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a 

Click Share and navigate to a .ink export page

-  Expected:
    1. scrolling reveals the ink pane contents on the page.
    2. Double-clicking inside the ink pane box selects the contents of the box.
-  Actual:
    1. The ink pane box extends off the bottom of the page, but the page will not scroll (and the textbox will not scroll), so part is always hidden.
    2. Double-click in the pane selects text on the entire page, not the pane contents.

Example: 
https://www.inklewriter.com/stories/5284.ink

* **What is the motivation / use case for changing the behavior?**
The preview pane means that the user can preview the export, and has the option to cut-paste ink rather than downloading the .ink. If the pane is only partially visible and not selectable then this inhibits these uses.

* **Please tell us about your environment:**
macOS Version 81.0.4044.129 (Official Build) (64-bit) 

This is a follow-up to #16 

<img width="1025" alt="Screen Shot 2020-05-07 at 10 18 35 AM" src="https://user-images.githubusercontent.com/798570/81324670-2754bb00-904c-11ea-8c44-e81d809abb36.png">

**Comment by maxence33** [comment]
Hi Jeremy. Indeed a few CSS tweaks needed. 
Now corrected in 613428c0345a0d51744b3927874247555d34ecab
Will be visible in next deployment

**Comment by maxence33** [comment]
We may also add a small "copy full content" icon so the .ink content can be copied easily.
But I am not familiar with .ink mime-type. I guess copy/paste should give exact same results as generated file though ..

**Comment by jeremydouglass** [comment]
> not familiar with .ink mime-type

Good point. `.ink` should be equivalent to text/plain, right?

**Comment by maxence33** [comment]
oh, actually we made the back-end know it as "text/html" so that we can redirect to the view where you can download the file.
The actual file is created by the conversion JS here https://www.inklestudios.com/inklewriter/to-ink/ so whatever the app knows about .ink,  it has no effect on the actual file content

Though my concern was I changed the view tag containing the data from "<pre></pre>" originally to "<div></div>". I have reinstated "pre" as I wasn't too if it would tamper the string

**Comment by jeremydouglass** [comment]
Looks good, works well.

A suggestion for `#result_ink` -- move it off the browser scrollbars, make it compact, and let it wrap long lines so that horizontal scroll isn't required. This visually wraps but on copy-paste this won't put wrapped lines on the clipboard.

```
    width: 90%;
    height: 200px;
    // ...
    overflow: scroll;
    white-space: pre-wrap;
```

...and also set  `#inkling textarea` off the browser scrollbars:

```
width: 90%
```

**Comment by maxence33** [comment]
Hi Jeremy
I have added your suggestions to the CSS. And also made a copy button.
1ae33f2782f69b8d9886e872a82611d62b410f6f
(visible in next deployment or from master)

**Comment by jeremydouglass** [comment]
Thank you so much. I will close this issue after looking at the next deploy.

**Comment by maxence33** [comment]
hi Jeremy. It is now live

**Comment by jeremydouglass** [comment]
Looks great, thank you. The copy to clipboard button is also a nice touch.
