### ISSUE TITLE
Shared Inkle Story doesn't Scroll Down Automatically

### ISSUE THREAD

**Issue by Erilis000** [inklewriter/freeinklewriter#26]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When I view my story in Read or Write mode it automatically scrolls down as new paragraphs are shown, however it does not auto-scroll when reading the shared version. Is that intentional? Bug?

* **What is the expected behavior?**
Automatically scroll down when progressing through the story, similarly to how it does when logged in and editing your story.

* **What is the motivation / use case for changing the behavior?**
Would be much more convenient for people I'm sharing the story with.

* **Please tell us about your environment:**
  
  - Version: 1.0
  - Browser: [Chrome XX ]

**Comment by albancrommer** [comment]
Thanks for the feedback. I hacked a solution that should work for mostly everyone, as it can be a bit tricky to position.

Should be available on the public instance in the coming 24 hours for everyone to test.

**Comment by albancrommer** [comment]
The site is up to date.

You can test on https://www.inklewriter.com/stories/29 

Comments are welcome.

**Comment by Erilis000** [comment]
That's amazing, thank you so much!

**Comment by albancrommer** [comment]
OK, well, not much feedback so I guess that settles it.

**Comment by jeremydouglass** [comment]
Belatedly tested on Chrome 84.0.4147.13 -- looks great.
