### ISSUE TITLE
Full Map View

### ISSUE THREAD

**Issue by JeffH1987** [inklewriter/freeinklewriter#31]
* **I'm submitting a ...**
  - [x ] feature request

* **Do you want to request a *feature* or report a *bug*?**

Feature Request

* **What is the current behavior?**

In the editor, the Map will essentially just show your current section and any immediately connected paragraphs.  All connected paragraphs may be selected to go to their sections. The zoom will of course zoom in and out of the viewed sections, and that is certainly useful if the section is very large.

* **What is the expected behavior?**

The request is to make it also possible to zoom out in a way that allows the user to see multiple interconnected sections and perhaps even the entire story web.

* **What is the motivation / use case for changing the behavior?**

This could be useful for seeing a broader birds eye view to help keep the story straight, as an alternative to scrolling through the Contents section. As in, you want to see details written in the prior section to ensure continuity in the current with possibly less scrolling and selecting within the Contents area. It might also be simply interesting to see the full web of the "entire" story.

* **Please tell us about your environment:**
  
  - Version: 1.0
  - Browser:  Chrome 88

**Comment by maxence33** [comment]
Hi Jeff, 

Thanks for submitting this enhancement proposal. We have a few things in the pipeline at the moment (mostly a community page) but we will review your enhancement proposal. Until now we have commited only minor changes to the core JS app (https://github.com/inklewriter/freeinklewriter/blob/master/app/assets/javascripts/inklewriter-write.js) and your proposal seem of a broader scope. 

We will come back to you asap on this. And in case we cannot proceed by ourselves but find your idea good, we will leave this case open so any one can submit their attempt. 

Best

**Comment by albancrommer** [comment]
The code complexity of the map view is too high to change anything about it. 

Sadly this is not something we can achieve.
