### ISSUE TITLE
Conditioning with negative values seems not to work.

### ISSUE THREAD

**Issue by Uocyar** [inklewriter/freeinklewriter#32]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] bug report
 

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When adding a value to a marker, and later inserting a condition with negatives numbers that should work with the value of the marker, the text associated with the condition in negative number will not be showed. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Maybe the problem comes from me, but here are the screenshots I took, with the writing/conditioning and the reading/result thing on the site. Sorry if I'm not doing this right.
Step 1: load an existing story
2: creating/changing a marker value on a text.
3: creating/changing a condition with negatives numbers that fits the marker value to display the text.
4: click on read to see if the text is shown.
5: the text isn't shown when the condition as a "-", a negative value in it.

![Capture d’écran 2021-03-13 à 01 58 26](https://user-images.githubusercontent.com/80555278/111013541-17aaaf00-83a0-11eb-8181-8063d52ce69a.png)
![Capture d’écran 2021-03-13 à 01 58 46](https://user-images.githubusercontent.com/80555278/111013543-1b3e3600-83a0-11eb-8259-aed94045f5e7.png)

* **What is the expected behavior?**
The conditionning should work with negatives numbers too, such as X>-1, X<-2, X=-3, and displaying the text associated

* **What is the motivation / use case for changing the behavior?**
Writing stories with negatives conditions.

* **Please tell us about your environment:**
  
  - Version: 1.21.73
  - Browser: [Brave]
  - Version: 89.0.4389.82
  - Browser: [Chrome]

**Comment by Uocyar** [comment]
Here are the steps I forgot to write:
Step 1: load an existing story
2: creating/changing a marker value on a text.
3: creating/changing a condition with negatives numbers that fits the marker value to display the text.
4: click on read to see if the text is shown.
5: the text isn't shown when the condition as a "-", or a negative value in it.

**Comment by albancrommer** [comment]
I have tested and confirmed this, see the [test story](https://www.inklewriter.com/stories/50561)

All operators fail to work with negative numbers to a regular expression quirk in the `StoryModel.test()` method.

The regexp goes like this `o = /^(.*?)\s*(\<|\>|\<\=|\>\=|\=|\!\=|\=\=)\s*(\b.*\b)\s*$/`

But the Word Boundary Metacharacter `\b` as used does not validate the minus (i.e. `-`) character as part of a word. 

Indeed, a number is not a word and I suspect the regexp is faulty.

This is not a trivial change though, as it might break a lot of stories at a lot of points.

**Comment by Uocyar** [comment]
So did I have to use a positive number to change the negative value, or wait for a changing in the code that might take a long time, if there's one ?

**Comment by albancrommer** [comment]
You'd better use positive numbers for now. 

This is the way inklewriter has been designed, and it works well like this.

We won't be too acting too quick on this. The solution has to be well tested before.

**Comment by Uocyar** [comment]
I understand. Thanks for the help
