### ISSUE TITLE
Copy-Paste Paragraphs as Paragraphs

### ISSUE THREAD

**Issue by JeffH1987** [inklewriter/freeinklewriter#33]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

Text pasted from an outside word processor looses paragraph formatting. Formatting such as italicized text is also lost in translation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem (video/gif)**

Copying multiple paragraphs from an outside word processor leads to a single block of text instead of expected paragraphs. Formatting is lost.

This tutorial unintentionally highlights the behavior multiple times: https://youtu.be/FqO6X2D6a_s?t=90 . Perhaps of note, it appears the instructor actually does not fix the formatting.

* **What is the expected behavior?**

Retaining the paragraph formatting from the source text.

* **What is the motivation / use case for changing the behavior?**

It can be rather tedious and at times difficult to recreate the lost formatting if the text was originally in multiple paragraphs. Forgetting or missing intended paragraphs breaks can be very easy. The alternative is to copy-paste not more than a couple paragraphs at a time -- if not just one, and while that is less difficult to reformat, that can feel even more tedious. Copy-pasting dialogue, which can be just single sentence paragraphs, makes this issue the most prevalent.

* **Please tell us about your environment:**
  
  - Version: 1.0
  - Browser: [Chrome 89.x ]
  - OS: macOS Big Sur 11.2.3

**Comment by albancrommer** [comment]
Sorry it took us a few days to ponder and test this. 

While we can see the use for copy/pasted paragraphs, we don't feel changing things about it.

We have retrieved the JS code from inklestudios' running production instance : code is complex, we don't fully understand it, we have no test bed (regressions and so on) to confirm changes are safe.

So our attitude with that code is conservative. So far it works as intended, minus inconveniences like this one.

I leave the discussion open but will close the bug in a few days.
