### ISSUE TITLE
A collaborative writer?

### ISSUE THREAD

**Issue by 100beeep** [inklewriter/freeinklewriter#36]
This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
I would like to request a feature.

* **What is the current behavior?**
The current behavior is that other people can only read your stories.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem (video/gif)**

* **What is the expected behavior?**
It's expected that others can only read your stories. However, I'd like to be able to write a collaborative CYOA story.

* **What is the motivation / use case for changing the behavior?**
I'd like to write a story that anyone can contribute to.

* **Please tell us about your environment:**
  
  - Version: 1.0
  - Browser: [all | Chrome XX]

* **Other information** (e.g. detailed explanation, stacktraces, related issues
Thanks for listening!

**Comment by albancrommer** [comment]
Thanks for that proposal.

It is a great idea, but sadly having a decent multi-author and collaborative story editor would mean to achieve simultaneous edits, like etherpad, and that is *way* out of the scope of this project. 

On the other hand, you could also share a single account with multiple authors to achieve non-simultaneous collaboration. 

You would have to signal by some mean (email, some paragraph, etc.) that X is currently editing the story for X hours.

But be cautious that multiple people editing the same story on different computers will only leave **one of the versions** in the database.

You could also use the export / import feature and work iteratively : 

* A writes the first version v1
* B imports A's version and edits it : now it is v2
* C imports v2 and edits it: now it is v3
* A imports v3, etc.
