### ISSUE TITLE
(feature request) persistence

### ISSUE THREAD

**Issue by TalonZane** [inklewriter/freeinklewriter#42]
feature: some kind of persistence between sessions would be very nice.

im dyslexic so it's really hard to use the program outside of night mode, and it sucks having to turn it back on every single time. some form a json file that keeps user info should also allow the user to set a default output location, which would speed things up nicely.

**Comment by albancrommer** [comment]
Are you sure you're speaking about inklewriter which this issue tracker is done for?

I don't think it has a night mode at all? Or do you have any screenshot ?

**Comment by TalonZane** [comment]
ah whoops, assumed inky and inklewriter were the same thing, sorry :(
