### ISSUE TITLE
Cannot import story from old version

### ISSUE THREAD

**Issue by Nevets1701** [inklewriter/freeinklewriter#43]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report?
  
I follow the steps of clicking share in the old site and adding .json to the link. But when I put it into my address bar it just opens the new inkle site. I am using Firefox.

**Comment by albancrommer** [comment]
Hi @Nevets1701 

Looks like it works, as an example for the "cccc" id on the old inklewriter

https://oldinklewriter.inklestudios.com/stories/cccc.json

What's your story URL -if it is something you can share) ?

**Comment by Selsynn** [comment]
So it seems your data is here 
https://oldinklewriter.inklestudios.com/stories/vvrv.json

At least you have a json there with a lot of data.

**Comment by Nevets1701** [comment]
Ah. Thank you very much.
