### ISSUE TITLE
Feature/help request: 'Rewind to here'-button on each segment

### ISSUE THREAD

**Issue by magnuspersson13** [inklewriter/freeinklewriter#46]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I'd like for the 'Rewind to here' feature to be available for each segment of text in 'read' mode (as it is in 'write' mode).

<img width="317" alt="Skärmavbild 2022-03-05 kl  15 04 29" src="https://user-images.githubusercontent.com/101005133/156886774-3fde6584-f042-490a-a5cd-8a5b711390e1.png">
<img width="161" alt="Skärmavbild 2022-03-05 kl  15 04 44" src="https://user-images.githubusercontent.com/101005133/156886781-7e2f7a42-00d9-445c-89bc-c80cbac83f8b.png">

* **What is the current behavior?**
When writing the story in 'write mode', there's a "Rewind to here"-arrow/button on each segment of text, allowing the writer to go back to any part of the text. This feature is not available in 'read' mode, other than to go back to the very beginning of the story.

* **What is the motivation / use case for changing the behavior?**
Adding 'Rewind to here' to each segment of text would allow the reader to go back to a previous choice and make a new one, rather than having to go all the way back to the beginning of the story.

* **Other information** (e.g. detailed explanation, stacktraces, related issues
This issue came up when I was testing a story of mine and I realised that when reading a physical gamebook, I'd be able to keep a finger at the previous segment so as to be able to go back and try another choice without having to replay the whole story from the beginning. It felt as if this may be something that was something that someone else might have thought about and also that it may not be very difficult to fix, given some knowledge of the code. Thus, I'd be interested in contact with someone who can help me/one of my programmer friends navigate the code so as to allow me to set up a server with this feature enabled. Grateful for any and all help I can get - Inklewriter is a great tool!

**Comment by albancrommer** [comment]
Sorry to have missed that issue. This is sadly too hard to do.

We retrieved the source code minified and without any documentation. We can fix small things, but new features are way too complex and we break a lot of stuff.

The best option to provide a better reading experience would be to provide a whole new frontend.
