### ISSUE TITLE
Inklewriter Servers Down on All Browsers?

### ISSUE THREAD

**Issue by ryangjheath** [inklewriter/freeinklewriter#66]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
 Report a bug

* **What is the current behavior?**

Unable to log in or view previously written stories via their link.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem (video/gif)**

![Screenshot 2024-09-17 101559](https://github.com/user-attachments/assets/0f7564a7-068f-4945-b8c2-be7b4cbcda07)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 1.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues

**Comment by albancrommer** [comment]
Sorry about that, it was another system default. The service is back.
